---
version: 2.1

jobs:

  build-android-armhf:
    docker:
      - image: circleci/android:api-28-ndk
    environment:
      - OCPN_TARGET: android-armhf
      - CMAKE_BUILD_PARALLEL_LEVEL: 2
    steps:
      - checkout
      - run: ci/circleci-build-android.sh
      - run: ci/maybe-push-upload.sh

std-filters: &std-filters
  filters:
    branches:
      ignore:
        - tmp
        - /tmp-.*/

workflows:
  version: 2
  build_all:
    jobs:

      - build-android-armhf:
          <<: *std-filters

